---
- name: update cache
  apt: 
    update_cache: yes

- name: Install git
  apt:
    name: git
    state: present
    update_cache: yes

- name: Install required docker system packages
  apt:
    pkg:
     - apt-transport-https
     - ca-certificates
     - curl
     - software-properties-common
     - python3-pip
     - virtualenv
     - python3-setuptools
    state: latest
    update_cache: true

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Install docker-ce
  apt:
    name: docker-ce
    state: latest
    update_cache: true

- name: Install Docker Module for Python
  pip:
    name: docker

- name: Docker usermod user
  ansible.builtin.command: sudo usermod -aG docker $USER

- name: Docker chmod docker.sock
  ansible.builtin.command: sudo chmod 666 /var/run/docker.sock

- name: Docker restart
  ansible.builtin.command: sudo service docker restart